---
title: "Getting_Started"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Getting_Started}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


Before we meet for our first class there are few things you should try at home to get started.

## Install R and R Studio

1. Download and install R on your computer. This is the R website [https://www.r-project.org](https://www.r-project.org)
2. Download and install R-studio. You must download and install R first before installing R-studio. The R-studio website is [https://www.rstudio.com](https://www.rstudio.com)

<iframe width="560" height="315" src="https://www.youtube.com/embed/VxsJYnQI0AE" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

## Github.com and Github Desktop

3. Create a free github account. The github website is [https://github.com](https://github.com)
4. Download and install github desktop [https://desktop.github.com](https://desktop.github.com)

## Test the pipeline

This semester students will be submitting their work as github repositories. Follow these steps to test the github pipeline to make sure it is working:

1. Create a new R project (initialize with git)
2. Create a new R Markdown document
3. Publish the R project folder on Github.com
4. Make commits and demonstrate that your local changes are reflected on github.com

<iframe width="560" height="315" src="https://www.youtube.com/embed/efQlpUomP94" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

## Why are we using R for this statistics lab?

A quick attempt to explain why I think it is totally worth it to learn R for data-analysis, and for psychologists in general.

<iframe width="560" height="315" src="https://www.youtube.com/embed/l_goAV71iKM" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

## RStudio run through

A look through some of the features of RStudio.

<iframe width="560" height="315" src="https://www.youtube.com/embed/hEhm5orkzMc" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

## Basic R programming overview

We will take a number of different approaches to using R to learn about statistics this semester. One of the approaches will be to learn about basic coding/scripting in R, which can become an entire course on its own. This video gives an impression of what coding looks and feels like in R Studio, and introduces some basic coding concepts such as variables, logic, loops, and functions.

<iframe width="560" height="315" src="https://www.youtube.com/embed/RRGKCcWY-_Q" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

## Practice problems

In addition to lab material, I will be posting additional screencasts here that provide more angles on learning R basics. For example, it can be useful to have specific problems thta you are trying to solve, and then set yourself the goal of figuring out how to solve the problems in R. I have a created a list of problems here <https://crumplab.github.io/programmingforpsych/programming-challenges-i-learning-the-fundamentals.html>. Some of the problems will be assigned in lab. Here, my plan to do some live coding, showing ways that I solve these problems. 

<iframe width="560" height="315" src="https://www.youtube.com/embed/50ElzpX7MOE" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<iframe width="560" height="315" src="https://www.youtube.com/embed/2k_K7rZezMU" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

