---
title: "Semester project Spring 2022"
output: rmarkdown::html_vignette
bibliography: BCStats.bib
csl: apa.csl
link-citations: yes
vignette: >
  %\VignetteIndexEntry{Semester project Spring 2022}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```
 
## Overview:

We will developing and discussing the semester long project throughout the semester. And, I will add more detail and instructions to the project on this page.

A major component will be using the R package [pkgdown](https://pkgdown.r-lib.org) to create a website (and more) to act as a portfolio for communicating and displaying the work you do this semester.

Last semester you completed your lab work as .Rmd documents, uploaded them to a Github Repository, and submitted the link to your repository to Blackboard. This semester will be similar, except we will be using an R package project structure, and saving the lab work in a specific folder called **vignettes**, and compiling your work to present it in the form of a website.

For now, watch this getting starting video to review the process. I will go over the details many times in class as well.

<iframe width="560" height="315" src="https://www.youtube.com/embed/jxWe_XuQSeI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

## Example Semester Project

I will be building my own semester project throughout the semester. This code-base can act as working example code for you. My semester project will be located here:

<https://github.com/CrumpLab/SemesterProject7709>



